/*
    Project 2
    Author: Shaan Arora C3236359
    Enum for STNode NodeValue
 */

public enum NodeValue
{
    NPROG,  NGLOB, NILIST, NINIT,  NFUNCS, NMAIN, NSDLST, NTYPEL, NRTYPE, NATYPE, NFLIST, NSDECL,
    NALIST, NARRD, NFUND,  NPLIST, NSIMP,  NARRP, NARRC,  NDLIST, NSTATS, NFOR,   NREPT,  NASGNS,
    NIFTH,  NIFTE, NASGN,  NPLEQ,  NMNEQ,  NSTEQ, NDVEQ,  NINPUT, NPRINT, NPRLN,  NCALL,  NRETN,
    NVLIST, NSIMV, NARRV,  NEXPL,  NBOOL,  NNOT,  NAND,   NOR,    NXOR,   NEQL,   NNEQ,   NGRT,
    NGEQ,   NLEQ,  NLSS,   NADD,   NSUB,   NMUL,  NDIV,   NMOD,   NPOW,   NILIT,  NFLIT,  NTRUE,
    NFALS, NFCALL, NPRLST, NSTRG
}
